name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - jupyterlab=4.2.2
  - mlflow=2.14.1
  - numpy=1.26.4
  - cookiecutter=2.6.0
  - hydra-core=1.3.2
  - matplotlib=3.8.4
  - pandas=2.2.2
  - git=2.45.1
  - pip=24.0
  - pip:
      - wandb==0.17.3
      - databricks_cli